version: '3.8'

services:
  po-todo-list:
    build: .
    container_name: po-todo-list-app
    ports:
      - "8081:8081"
    volumes:
      # 数据持久化 - SQLite数据库文件
      - ./data:/app/data
      # 日志持久化
      - ./logs:/app/logs
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m -Djava.security.egd=file:/dev/./urandom
      - SERVER_PORT=8081
      - TZ=Asia/Shanghai
      # 确保SQLite数据库路径正确挂载
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/potodo.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  todo-data:
    driver: local